import onnxruntime as ort
import numpy as np
import cv2
from config import REIDConfig
from typing import Union, List


class ReIDModel:
    def __init__(self, model_path: str, config: Union[REIDConfig, None] = None):
        """
        Initializes the ReIDModel class with the ONNX model and configuration parameters.
        Args:
            model_path (str): Path to the ONNX model file.
            config (REIDConfig, optional): Configuration parameters for ReID. Defaults to None.
        
        """
        self.config = config or REIDConfig()
        
        self.__dict__.update(vars(self.config))

        self.device = self.config.device

        if self.device == "cuda":
            providers = ['CUDAExecutionProvider']
        elif self.device == "cpu":
            providers = ['CPUExecutionProvider']  
        else:
            raise ValueError(f"Unsupported device: {self.device}. Use 'cpu' or 'cuda'.")  

        self.session = ort.InferenceSession(model_path, providers=providers)  # use 'CUDAExecutionProvider' if GPU
        self.input_name = self.session.get_inputs()[0].name

        self.mean = np.array(self.config.mean)
        self.std = np.array(self.config.std)

        self.image_size = self.config.image_size
        self.batch_size = self.config.batch_size


    def preprocess(self, image: np.ndarray, bbbox: List[List[float]]) -> List[np.ndarray]:
        """ Preprocesses the input image and bounding boxes to create crops suitable for ReID model inference.
        Args:
            image (np.ndarray): The input image from which to extract crops.
            bbbox (List[List[float]]): List of bounding boxes, where each box is represented as [x_center, y_center, width, height, confidence].
        Returns:
            List[np.ndarray]: List of preprocessed image crops suitable for ReID model inference.
        """

        width, height = image.shape[1], image.shape[0]
        
        crops = []
        for det in bbbox: 
            x, y, w, h, _ = det
            x1 = x - w / 2
            y1 = y - h / 2
            x2 = x + w / 2
            y2 = y + h / 2

            x1 = max(int(x1), 0)
            y1 = max(int(y1), 0)
            x2 = min(int(x2), width)
            y2 = min(int(y2), height)

            crop = image[y1:y2, x1:x2]

            crop = cv2.resize(crop, self.image_size)

            crop = crop[:, :, ::-1].astype(np.float32) / 255.0
            crop = (crop - self.mean) / self.std
            crop = np.transpose(crop, (2, 0, 1))
            crops.append(crop)
        return crops
    
    def infer(self, crops: List[np.ndarray]) -> np.ndarray:
        """ Performs inference on the preprocessed image crops using the ONNX ReID model.
        Args:
            crops (List[np.ndarray]): List of preprocessed image crops.
        Returns:
            np.ndarray: Array of embeddings generated by the ReID model for each crop.
        """
        outputs = []
        for i in range(0, len(crops), self.batch_size):
            batch_crops = crops[i:i + self.batch_size]
            batch = np.stack(batch_crops).astype(np.float32)
            output = self.session.run(None, {self.input_name: batch})
            outputs.append(output[0])
        embeddings = np.vstack(outputs)
        return embeddings

    @staticmethod  
    def postprocess(embeddings: np.ndarray) -> np.ndarray:
        """ 
        Post-processes the raw embeddings from the ReID model by applying L2 normalization.
        Args:
            embeddings (np.ndarray): Raw embeddings output from the ReID model.
        Returns:
            np.ndarray: L2-normalized embeddings suitable for similarity comparison."""
        
        norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
        embeddings = embeddings / (norms + 1e-8)
        return embeddings


    def __call__(self, image: np.ndarray, bbbox: List[List[float]]) -> np.ndarray:
        """
        Processes the input image and bounding boxes through the entire ReID pipeline: preprocessing, inference, and post-processing.
        Args:
            image (np.ndarray): The input image from which to extract crops.
            bbbox (List[List[float]]): List of bounding boxes, where each box is represented as [x_center, y_center, width, height, confidence].
        Returns:
                np.ndarray: Final array of L2-normalized embeddings for the input bounding boxes."""
        if len(bbbox) == 0:
            return np.array([])
        
        crops = self.preprocess(image, bbbox) 
        embeddings = self.infer(crops)
        embeddings = self.postprocess(embeddings)
        return embeddings
    